function ax=make_axes(nTileX,nTileY,figWidth,deltaX,deltaX2,deltaY,deltaY2,gapX,gapY,panel_scale)

%    nTileX=1;
%    nTileY = 2;
%        
%    %figWidth = 3.3; % in inches, for AGU single-column figures
%    figWidth = 6.5; %6.5 inches = 39 picas, for a two column figure
%    %figWidth = 9.5; %6.5 inches = 39 picas, for a two column figure
%    deltaX   = 0.7;
%    deltaX2  = 0.1;
%    deltaY   = 0.5;
%    deltaY2  = 0.2;
%    gapX     = 0.6;
%    %gapX=0.3;
%    gapY     = 0.4;
    panelX   = ( figWidth - deltaX - deltaX2 - ( nTileX -1 ) * gapX ) / nTileX; 
    %panelY   = panelX * ( 3 / 4 ) ^2;
    %panelY=panelX*0.3;
    panelY=panelX*panel_scale;
    posn     = [ 0, ...
                 0, ...
                 nTileX * panelX + ( nTileX - 1 ) * gapX + deltaX + deltaX2, ...
                 nTileY * panelY + ( nTileY - 1 ) * gapY + deltaY + deltaY2 ];

    fig = figure( 'units', 'inches', ...
                  'paperPosition', posn, ...
                  'position', posn, ...
                  'defaultAxesNextPlot', 'add', ...
                  'defaultAxesBox', 'on', ...
                  'defaultAxesFontSize', 12, ...
                  'defaultTextFontSize', 12, ...
                  'defaultAxesTickDir', 'out', ...
                  'defaultAxesTickLength', [ 0.01 0 ], ...
                  'defaultAxesFontName', 'times', ...
                  'defaultTextFontName', 'times', ...
                  'defaultAxesLineWidth', .5, ...
                  'defaultAxesLayer', 'top' );

%    fig = figure( 'units', 'inches', ...
%                  'paperPosition', posn, ...
%                  'position', posn, ...
%                  'defaultAxesNextPlot', 'add', ...
%                  'defaultAxesBox', 'on', ...
%                  'defaultAxesFontSize', 12, ...
%                  'defaultTextFontSize', 12, ...
%                  'defaultAxesTickDir', 'out', ...
%                  'defaultAxesTickLength', [ 0 0 ], ...
%                  'defaultAxesFontName', 'times', ...
%                  'defaultTextFontName', 'times', ...
%                  'defaultAxesLineWidth', .5, ...
%                  'defaultAxesLayer', 'top' );

    ax = zeros( nTileX, nTileY );

    for iAx = 1 : nTileX
        for jAx = 1 : nTileY
            ax( iAx, jAx ) = axes( 'units', 'inches', ...
                                   'position', [ deltaX + ( iAx - 1 ) * ( panelX + gapX ), ...
                                    deltaY + ( nTileY - jAx ) * ( panelY + gapY ), ...
                                    panelX, panelY ] );
        end
    end






